# See https://ezcv.readthedocs.io for documentation
name: Maliha Homaira
theme: strata
resume: true
avatar: https://w7.pngwing.com/pngs/516/431/png-transparent-female-profile-avatar-illustration-computer-icons-female-user-profile-female-girl-wife-woman-icon-miscellaneous-logo-monochrome-thumbnail.png # A path to an image of yourself (can also be a URL)
biography: A machine learning enthusiast # This field is for writing about yourself you can add a > to span multiple lines
